### ISSUE TITLE
最小权限时,只有一个数据库的只读权限时，无法获取数据库名

### ISSUE THREAD

**Issue by kebyn** [cookieY/Yearning#105]
```
2019-01-15 14:05:58,853 [MainThread:140047206169480]                       [django.request:118] [ERROR]- Internal Server Error: /api/v1/query_worklf
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/mnt/src/core/api/serachsql.py", line 283, in put
    db=i['Database']) as f:
KeyError: 'Database'
```

**Comment by cookieY** [comment]
@kebyn 请告知具体场景

**Comment by kebyn** [comment]
> @kebyn 请告知具体场景

在只有一个数据库的读写权限时，发生这个错误
>> 可能原因是无法是在python中 show databases; 为空

**Comment by cookieY** [comment]
@kebyn 用最新版本试试

**Comment by cookieY** [comment]
@kebyn 你需要先点击对应查询的库名后再输入SQL 查询才可以

**Comment by kebyn** [comment]
@cookieY 进入查询界面库名显示为空 导致无法点击库名进行选择数据库

**Comment by cookieY** [comment]
@kebyn 请确认连接名用户是否具有读数据库的权限以及连接名下是否有数据库

在相同版本相同情况 重新测试并没有发现此问题,无法复现此类问题。请着重检查环境问题
