### ISSUE TITLE
查询不存在的数据报错

### ISSUE THREAD

**Issue by ajie551** [cookieY/Yearning#110]
![image](https://user-images.githubusercontent.com/42767709/54414140-19025c00-4733-11e9-9ba9-8afdf9305a06.png)
![image](https://user-images.githubusercontent.com/42767709/54414144-20c20080-4733-11e9-901f-b0ab0c3dfd90.png)
查询不存在的数据报错

2019-03-15 14:53:13,737 [Thread-176:139881970789096]                       [django.request:118] [ERROR]- Internal Server Error: /api/v1/search               
Traceback (most recent call last):                                                                                                                           
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner                                                               
    response = get_response(request)                                                                                                                         
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response                                                           
    response = self.process_exception_by_middleware(e, request)                                                                                              
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response                                                           
    response = wrapped_callback(request, *callback_args, **callback_kwargs)                                                                                  
  File "/usr/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view                                                          
    return view_func(*args, **kwargs)                                                                                                                        
  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view                                                                     
    return self.dispatch(request, *args, **kwargs)                                                                                                           
  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch                                                                     
    response = self.handle_exception(exc)                                                                                                                    
  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 454, in handle_exception                                                             
    self.raise_uncaught_exception(exc)                                                                                                                       
  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 491, in dispatch                                                                     
    response = handler(request, *args, **kwargs)                                                                                                             
  File "/mnt/src/core/api/serachsql.py", line 132, in post                                                                                                   
    for k, v in data_set['data'][0].items():

**Comment by cookieY** [comment]
请下载最新版本
