### ISSUE TITLE
点击"我的工单"-->"驳回理由"报错，无法查看驳回理由

### ISSUE THREAD

**Issue by 203HAHA** [cookieY/Yearning#188]
报错如下：

![image](https://user-images.githubusercontent.com/48740082/69020961-3b9af200-09f1-11ea-9e50-4c7eefec5770.png)
![image](https://user-images.githubusercontent.com/48740082/69020993-4f465880-09f1-11ea-9f0a-7612be8e30f1.png)

"ReferenceError: n is not defined
   at eval (eval at show (http://172.16.224.211/js/chunk-vendors.d45b4b29.js:68:442313), <anonymous>:1:1)
   at Object.show (http://172.16.224.211/js/chunk-vendors.d45b4b29.js:68:442313)
   at l (http://172.16.224.211/js/chunk-vendors.d45b4b29.js:68:439083)
   at Object.r.default.error (http://172.16.224.211/js/chunk-vendors.d45b4b29.js:68:439631)
   at orderReject (http://172.16.224.211/js/chunk-eaaaba94.6d12093c.js:1:5934)
   at click (http://172.16.224.211/js/chunk-eaaaba94.6d12093c.js:1:2860)
   at rt (http://172.16.224.211/js/chunk-vendors.d45b4b29.js:18:11758)
   at o.n (http://172.16.224.211/js/chunk-vendors.d45b4b29.js:18:13570)
   at rt (http://172.16.224.211/js/chunk-vendors.d45b4b29.js:18:11758)
   at o.In.e.$emit (http://172.16.224.211/js/chunk-vendors.d45b4b29.js:18:26566)"

**Comment by cookieY** [comment]
已修复，将随下个版本放出
