### ISSUE TITLE
权限申请和添加字段默认值报错

### ISSUE THREAD

**Issue by nimei1248** [cookieY/Yearning#23]
问题1: 在个人信息中修改用户，如，admin权限申请报错如下:

# python3 -V
Python 3.6.4

2018-04-16 13:50:17,874 [Thread-20:140082289620736]                       [django.request:118] [ERROR]- Internal Server Error: /api/v1/apply_grained/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/python3/lib/python3.6/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/python3/lib/python3.6/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/yearning/src/core/api/applygrained.py", line 77, in post
    thread = threading.Thread(target=push_message, args=({'to_user': request.user, 'workid': work_id}, 2, request.user, mail.email, work_id, '已提交'))
AttributeError: 'NoneType' object has no attribute 'email'
2018-04-16 13:50:17,904 [Thread-20:140082289620736]                       [django.server:124] [ERROR]- "POST /api/v1/apply_grained/ HTTP/1.1" 500 16085

/usr/local/yearning/src/core/api/applygrained.py:
class apply_grained(baseview.BaseView):

    def post(self, request, args: str = None):

        grained_list = json.loads(request.data['grained_list'])
        work_id = util.workId()
        applygrained.objects.get_or_create(work_id=work_id, username=request.user, permissions=grained_list, status=2)
        mail = Account.objects.filter(id=1).first()
        thread = threading.Thread(target=push_message, args=({'to_user': request.user, 'workid': work_id}, 2, request.user, mail.email, work_id, '已提交'))
        thread.start()
        return Response('权限申请已提交!')

问题2: 在工单提交--DDL中添加字段，如果选择不为空，默认值设置为空字符串''时就会多加一对单引号，如下:
如果默认值为"，就会变成'"'
SQL> show create table t2\G
*************************** 1. row ***************************
       Table: t2
Create Table: CREATE TABLE `t2` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `name2` varchar(5) NOT NULL DEFAULT '' COMMENT 'name',
  `group2` varchar(5) NOT NULL DEFAULT '''' COMMENT 'group2',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COMMENT='t2'
1 row in set (0.00 sec)

请作者帮忙解惑，谢谢

**Comment by cookieY** [comment]
1.在工单提交--DDL中添加字段，如果选择不为空，默认值设置为空字符串''时就会多加一对单引号

如果默认值为空字符串则 直接在填写空格内 敲一个空格就行 不需要自行加''

2.个人中心处申请权限 并没有admin 这项 不知道具体是哪项？

**Comment by cookieY** [comment]
@nimei1248  已发现问题，如果admin 没有邮箱地址的话会发生。下个版本将会修复

**Comment by nimei1248** [comment]
谢谢 cookieY
