### ISSUE TITLE
2.2.0提交ddl时Juno报错崩溃

### ISSUE THREAD

**Issue by qingqidai** [cookieY/Yearning#295]
**Describe the bug**
**描述Bug**
DDL工单，提交create database  xxx 点击检测语句，后端juno崩溃

**To Reproduce**
**如何复现**

**Expected behavior**
**期望的结果**
ddl能够正常提交，语句检测

**Screenshots**
**截图**
` panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x883a02]

goroutine 26 [running]:
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.13.5/src/database/sql/sql.go:3063 +0x72
database/sql.(*Rows).Close(0x0, 0xc00011a780, 0x0)
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.13.5/src/database/sql/sql.go:3059 +0x33
panic(0x1254280, 0x25d6a10)
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.13.5/src/runtime/panic.go:679 +0x1b2
database/sql.(*Rows).Next(0x0, 0x1)
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.13.5/src/database/sql/sql.go:2744 +0x30
Juno/parser.(*YerningAuditOrder).mysqlServerVersion(0xc0001c5540)
	/var/jenkins_home/workspace/Juno/parser/fetchRemote.go:198 +0x13b
Juno/parser.(*YerningAuditOrder).New(0xc0001c5540, 0x0, 0x40dab6, 0x0)
	/var/jenkins_home/workspace/Juno/parser/parser.go:214 +0x2af
Juno/libraGrpc/server.(*Ser).OrderDeal(0x2651bb0, 0x1622900, 0xc000153710, 0xc000110000, 0x0, 0x0, 0x0)
	/var/jenkins_home/workspace/Juno/libraGrpc/server/server.go:191 +0x445
Juno/libraGrpc/proto._Juno_OrderDeal_Handler(0x12e38e0, 0x2651bb0, 0x1622900, 0xc000153710, 0xc00008c9c0, 0x0, 0x1622900, 0xc000153710, 0xc00004e600, 0x55)
	/var/jenkins_home/workspace/Juno/libraGrpc/proto/detection.pb.go:618 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000170000, 0x1635020, 0xc0000a1680, 0xc0001d0000, 0xc0000adce0, 0x25eece0, 0x0, 0x0, 0x0)
	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1007 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc000170000, 0x1635020, 0xc0000a1680, 0xc0001d0000, 0x0)
	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1287 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002060c0, 0xc000170000, 0x1635020, 0xc0000a1680, 0xc0001d0000)
	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:722 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:720 +0xa1`

**Desktop (please complete the following information):**
**环境**

**Additional context**
**其他**

**Comment by qingqidai** [comment]
mysql从5.5升级到5.7，需要重新初始化数据
