### ISSUE TITLE
执行DML sql检测的时候juno进程panic

### ISSUE THREAD

**Issue by lethe3000** [cookieY/Yearning#368]
**Describe the bug** **描述Bug**
执行DML sql检测的时候juno进程panic

**To Reproduce** **如何复现**
juno镜像
```
FROM alpine:3.12

LABEL maintainer="HenryYee-2020/07/03"

EXPOSE 8000

COPY juno  /opt/juno
COPY conf.toml /opt/conf.toml

RUN echo "http://mirrors.ustc.edu.cn/alpine/v3.12/main/" > /etc/apk/repositories && \
      apk add --no-cache tzdata libc6-compat && \
      ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
      echo "Asia/Shanghai" >> /etc/timezone && \
      echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

WORKDIR /opt

ENTRYPOINT  ["/opt/juno"]

CMD ["-p", "50001"]
```
juno为最新版本, md5: 7bcdba526e8e70abd87c724bc0262185

启动yearning主程序，使用yearning-gemini master最新版本构建的dist
执行DML创建，在测试sql: `update core_accounts set email='admin@1.cn' where username='admin';`的时候juno镜像异常退出。

**Expected behavior** **期望的结果**
juno正确返回测试结果

**错误日志**
```
juno_1      | panic: runtime error: invalid memory address or nil pointer dereference
juno_1      | [signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x8a4986]
juno_1      |
juno_1      | goroutine 44 [running]:
juno_1      | github.com/jinzhu/gorm.(*DB).Close(0x0, 0x40, 0x12be6c0)
juno_1      | 	/var/jenkins_home/go/pkg/mod/github.com/jinzhu/gorm@v1.9.12/main.go:118 +0x26
juno_1      | Juno/libraGrpc/server.(*Ser).OrderDeal.func1(0xc0005d5600)
juno_1      | 	/var/jenkins_home/workspace/juno/libraGrpc/server/server.go:180 +0x33
juno_1      | Juno/libraGrpc/server.(*Ser).OrderDeal(0x25fb930, 0x15cba80, 0xc00018ccf0, 0xc0001345a0, 0xc000046440, 0x0, 0x0)
juno_1      | 	/var/jenkins_home/workspace/juno/libraGrpc/server/server.go:201 +0x362
juno_1      | Juno/libraGrpc/proto._Juno_OrderDeal_Handler(0x12ba940, 0x25fb930, 0x15cba80, 0xc00018ccf0, 0xc00008a7e0, 0x0, 0x15cba80, 0xc00018ccf0, 0xc00014a100, 0x7e)
juno_1      | 	/var/jenkins_home/workspace/juno/libraGrpc/proto/detection.pb.go:559 +0x217
juno_1      | google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001b00, 0x15dd140, 0xc0003fa600, 0xc000244000, 0xc000275f80, 0x258ab40, 0x0, 0x0, 0x0)
juno_1      | 	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024 +0x501
juno_1      | google.golang.org/grpc.(*Server).handleStream(0xc000001b00, 0x15dd140, 0xc0003fa600, 0xc000244000, 0x0)
juno_1      | 	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313 +0xd3d
juno_1      | google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000614150, 0xc000001b00, 0x15dd140, 0xc0003fa600, 0xc000244000)
juno_1      | 	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0xa1
juno_1      | created by google.golang.org/grpc.(*Server).serveStreams.func1
juno_1      | 	/var/jenkins_home/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:720 +0xa1
```

**Desktop (please complete the following information):** **环境**
 - OS: osx
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: yearning master/2af94a9

**Additional context** **其他**

**Comment by lethe3000** [comment]
执行DDL测试juno也有类似错误

**Comment by lethe3000** [comment]
在非mac docker的下未遇到该问题，使用slim镜像也未遇到问题
