### ISSUE TITLE
juno在执行sql检测的时候，出现运行异常

### ISSUE THREAD

**Issue by mintrumpet** [cookieY/Yearning#775]
**Describe** **描述**

在执行SQL检测的时候，juno抛出了运行异常，最终整个进程结束。

```
level=error msg="dial tcp :0: connect: connection refused" file="/Users/henryyee/PersonalProjects/enginex/parse/parse.go:232"

panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe82a60]

goroutine 80 [running]:
Juno/impl.(*Review).Exec.func1()
        /Users/henryyee/PersonalProjects/Juno/impl/exec.go:108 +0x20
panic({0xf872c0, 0x200c130})
        /usr/local/go/src/runtime/panic.go:884 +0x212
Juno/impl.(*Review).Exec(0xc0004a6e40)
        /Users/henryyee/PersonalProjects/Juno/impl/exec.go:110 +0xbb
Juno/impl.(*Review).Executor.func1()
        /Users/henryyee/PersonalProjects/Juno/impl/exec.go:99 +0x6c
created by Juno/impl.(*Review).Executor
        /Users/henryyee/PersonalProjects/Juno/impl/exec.go:84 +0x5a
```

**Comment by cookieY** [comment]
该数据源无法连接 请检查相关数据源配置信息

**Comment by mintrumpet** [comment]
运行的时候是已经连接的了？是否有可能在过程中出现连接失败的情况？
