### ISSUE TITLE
无法发送邮件推送

### ISSUE THREAD

**Issue by veryrich** [cookieY/Yearning#88]
您好，在后台测试发送邮件的时候，提示Network Err，

Chrome看了下POST地址和数据分别是：
```shell
# URL:
http://172.16.1.38:8000/api/v1/setting/3

# DATA:
mail:"{"webhook":"","smtp_host":"smtp.exmail.qq.com","smtp_port":"465","user":"123@123.com","password":"123","to_user":"123@123.com","mail":true,"ding":false}"

# 账号密码经过处理
```

Django日志报错：
```shell
2018-12-17 04:14:35,741 [MainThread:140514475801480]
[django.request:118] [ERROR]- Internal Server Error: /api/v1/setting/3

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/usr/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/usr/lib/python3.6/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/lib/python3.6/site-packages/rest_framework/renderers.py", line 717, in render
    template = loader.get_template(self.template)
  File "/usr/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
```

直接访问post网址报错：
![image](https://user-images.githubusercontent.com/12951051/50068012-c6caa100-01fe-11e9-9f29-da4accf15016.png)

**Comment by cookieY** [comment]
@veryrich 此错误与邮件推动无关，请检查自己的配置信息
